sudo: false

language: node_js
node_js:
  - "6"
  - "8"
  - "10"

env:
  - ESLINT_VERSION=^4.19.1
  - ESLINT_VERSION=^5.0.0

before_script:
  - npm i --no-save eslint@$ESLINT_VERSION; true

script:
  - if [ $ESLINT_VERSION = ^5.0.0 ]; then npm run lint; fi
  - npm test

after_success:
  - npm run codecov

before_deploy:
  - rm -rf node_modules
  - yarn
  - yarn run docs:build

deploy:
  provider: pages
  github-token: $ATOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master
    node: "10"
    condition: $ESLINT_VERSION = ^5.0.0
  skip-cleanup: true
